name: movie_db_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^4.0.4
  url_launcher: ^6.0.17
  readmore: ^2.1.0
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  uni_links: ^0.5.1
  shimmer: ^2.0.0
  fluttertoast: ^8.0.8
  photo_view: ^0.14.0
  carousel_slider: ^4.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icons/ic_app_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/